### ISSUE TITLE
Buffering

### ISSUE THREAD

**Issue by dayvsonsales** [lxieyang/ionic-audio-player#4]
Hello, 

This application support play audio from external url without complete downloading them first?

**Comment by lxieyang** [comment]
I think what it does is that it will download the audio from the url to the device's storage and then play them.

**Comment by dayvsonsales** [comment]
Oh, thank you for your answer. I thought that it could play the audio without complete download it first because I'm working on an application but I'm having problems dealing with audio buffering in iOS.

**Comment by lxieyang** [comment]
yeah, audio buffering can be problematic sometimes, but good luck to your project!
